version: '3.8'

services:
  {{COMPOSE_PROJECT_NAME}}-app:
    container_name: {{COMPOSE_PROJECT_NAME}}-app
    restart: always
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./../__logs/app:/app/__logs
    environment:
      - STREAMLIT_RELEASE=1
    networks:
      - web

  {{COMPOSE_PROJECT_NAME}}-nginx:
    container_name: {{COMPOSE_PROJECT_NAME}}-nginx
    restart: always
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    environment:
      - COMPOSE_PROJECT_NAME={{COMPOSE_PROJECT_NAME}}
    volumes:
      - ./nginx/nginx.conf--generated:/etc/nginx/nginx.conf
      - ./../__logs/nginx:/var/log/nginx
    depends_on:
      - {{COMPOSE_PROJECT_NAME}}-app
    ports:
      - "8080:80"
    networks:
      - web

networks:
  web:
    external: true
